tls_server_config:
  cert_file: node_exporter.crt
  key_file: node_exporter.key
basic_auth_users:
  farag: $6$sSEwTKaDimZpCyEK$mhNuoHl94SUz0VrQamqzjG0PaVkNLHYJ6hKPAvps/3FBCnFqEJJCdL5OQ5GZ8OcJMtggDPq6P/aNZAC10Psxj0
